### PR TITLE
Removing getting console color to support cross-plat

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by Eilon** [comment]
Should this go to the real xunit or what? How far behind are we from real xunit? Should we push there, then update our fork?

**Comment by BrennanConroy** [comment]
I added a PR there too, haven't gotten a response yet.

**Comment by Eilon** [comment]
Ok, I pinged Brad on https://github.com/xunit/dnx.xunit/pull/32 to see if he can review that.

In the meantime I guess this is fine, but after Brad takes that PR (hopefully!) we should update our fork to the latest official xUnit.net bits.

**Comment by Eilon** [comment]
Brad merged the PR on his side. Do we close this, and instead update our fork to the latest dnx.xunit?

**Comment by BrennanConroy** [comment]
I'm not sure, probably update our fork. But then do we also update the name? If we do we'll need to do a lot of changes everywhere

**Comment by Eilon** [comment]
@bricelam what's the usual pattern we have for updating our fork? Can you walk @BrennanConroy through the steps? And maybe we can put those on a wiki somewhere? (If it's not already.)

**Comment by bricelam** [comment]
Aren't we getting rid of our forks? @DamianEdwards said we should be using the nightly builds of xUnit.net.

**Comment by Eilon** [comment]
I think the plan is to just move a few of our repos over to the official xUnit.net and see how that plays out. Once we have high confidence, we can abandon this fork and switch everything over.

**Comment by kichalla** [comment]
Can we get this in as I hit this issue yesterday? I tried using the official version, but ran into a Null ref issue https://github.com/xunit/dnx.xunit/issues/45

**Comment by bricelam** [comment]
@kichalla Feel free to update to the xUnit.net nightly builds. See aspnet/Microsoft.Data.Sqlite@aae372cdb526b43ae5aff578d803ca126e18b883 for an example of how to do this.

**Comment by Eilon** [comment]
Do the xUnit nightly builds have this fixed? Or do we need to send a PR to xUnit for that?

**Comment by BrennanConroy** [comment]
We already did the fix on the official xunit side... the problem is they hard code the dnx version they build with and don't update as often as us, so often our tests wont run because xunit isn't up to date.

**Comment by kichalla** [comment]
Thanks you all !...pointing to Xunit night builds fixed the issue for me...

**Comment by dougbu** [comment]
@BrennanConroy we shouldn't need this anymore.

**Pull request closed without merging**
